### ISSUE TITLE
Debug.log 中文乱码 以及使用 gameObject.AddComponent报错

### ISSUE THREAD

**Issue by relic-yuexi** [GlossMod/UnityGameUI#5]
```c#
        // 加载时调用
        gameObject = new GameObject($"cn.moontidef.tweaktool{DateTime.Now.Ticks}");

        gameObject.AddComponent<MainWindow>();
```
```
System.TypeInitializationException: The type initializer for 'MethodInfoStoreGeneric_AddComponent_Public_T_0`1' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   --- End of inner exception stack trace ---
   at UnityEngine.GameObject.AddComponent[T]()
   at TweakTool.Plugin.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(PluginInfo pluginInfo, Assembly pluginAssembly) in /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.IL2CPP/IL2CPPChainloader.cs:line 134
   at BepInEx.Bootstrap.BaseChainloader`1.LoadPlugins(IList`1 plugins) in /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:line 411
```
解决方法,使用 this.AddComponent<MainWindow>();

可能原因: using BepInEx.Unity.IL2CPP;

**Comment by relic-yuexi** [comment]
中文乱码解决方法:
在最初始化的地方加上 
`Console.OutputEncoding = Encoding.UTF8;`
让Console默认为UTF8格式
